### ISSUE TITLE
Research/Build Rocket League replay file parsers

### ISSUE THREAD

**Issue by gitschaub** [RocketSportsAssociation/PocketCoach#1]
Understand the format and information of a replay file.

Things we may want (loosely):
- Able to track position of all players + ball
- Detect collisions? Player/player, player/ball
- If boost is being used

Two options for building:
1. Build our own: [information on format](http://www.psyonix.com/forum/viewtopic.php?f=33&t=13656)
2. Use an existing library: [Python lib used by rocketleaguereplays.com](https://github.com/rocket-league-replays/rocket-league-replay-parser)

**Comment by jenniebrown** [comment]
No sense in reinventing the wheel. 

Might also need orientation, speed. I assume altitude is included in position. Will also need to detect goals, clears, saves, etc.

**Comment by stephenrlouie** [comment]
Contingent on #2 
- CoreOS - DIY
- Python - We can leverage that library, but it seems pretty bare bones as is. Not even sure if it has what we really want. I don't know how helpful the below attributes are for what we want. When we pull the data I think we should try to keep it as raw as we can within reason, so the analysis can be open to the full set of data. The replay interpreter should simple take the byte data and convert to primatives of the language we chose.
  - level_info
  - key_frames 
  - network_stream
  - debug_strings
  - goal_ticks
  - packages
  - objects
  - name_table
  - classes
  - property_tree

**Comment by jenniebrown** [comment]
Have you guys seen the playback feature on rocketleaguereplays.com? They also have boost analysis going.

https://www.rocketleaguereplays.com/replays/450da37b-44a9-7876-6e59-548aa4baa99b/playback/

repo here: https://github.com/rocket-league-replays/rocket-league-replays

**Comment by gitschaub** [comment]
RL is built in UE4. Can learn about the network information by reading up on multiplayer/network docs: https://docs.unrealengine.com/latest/INT/Gameplay/Networking/

**Comment by stephenrlouie** [comment]
see #6 #7
