### ISSUE TITLE
Choose core project langauge

### ISSUE THREAD

**Issue by gitschaub** [RocketSportsAssociation/PocketCoach#2]
What language should the bread-and-butter of the project be written in?

Need to discuss trade-offs.

Golang:
_Pros:_ It's hip and cool, and multi-platform. Good with bit manipulation. And I want it.
_Cons:_ Not as many people are up to speed with it yet.

Python:
_Pros:_ Commonly used for machine learning applications. Everyone and their mom knows Python.
_Cons:_ Bit manipulation can be clunky. Jennie mildly doesn't like it.

**Comment by stephenrlouie** [comment]
Golang: Productivity, Integrity, Performance, Tooling

**Comment by gitschaub** [comment]
It's Go

**Comment by stephenrlouie** [comment]
It's a Go
